#' Prepare PDB file for crosslinked distance measurements
#'
#' Searches for pdb file in the pdbFileDir and if it fails to find it there,
#' downloads from the pdb repository. Works with either pdb or mmCIF formatted
#' files. Retains only Calpha coordinates. Wrapper for functions in the `Bio3d` package.
#'
#' @param pdbID Code for pdb/cif file
#' @param pdbFileDir Path to local directory containin pdb/cif file
#' @return A data frame.
#' @export
#'
parsePDB<- function(pdbID=NA, pdbFileDir=getwd()) {
  if (missing(pdbID)) {
    stop("read.pdb: please specify a PDB 'file' for reading")
  }
  pdbSplit <- unlist(stringr::str_split(pdbID, stringr::fixed(".")))
  if (length(pdbSplit) > 1) {
    pdbExtension <- pdbSplit[length(pdbSplit)]
    if (!pdbExtension %in% c("cif", "pdb")) pdbExtension <- "pdb"
    pdbFront <- pdbSplit[-length(pdbSplit)]
  } else {
    pdbFront <- pdbID
    pdbExtension <- "pdb"
  }
  pdbFile <- stringr::str_c(pdbFront, pdbExtension, sep=".")
  if (file.exists(file.path(pdbFileDir, pdbFile))) {
    parsedPDB <- tryCatch(
      switch(pdbExtension,
             "cif" = bio3d::read.cif(file.path(pdbFileDir, pdbFile), verbose=F),
             "pdb" = bio3d::read.pdb(file.path(pdbFileDir, pdbFile), verbose=F)
      ),
      error = function(e) {
        message(stringr::str_c("Trouble reading pdb id: ", pdbCode, "\n", e))
        return(NA)
      }
    )
  } else {
    pdbCode = stringr::str_extract(pdbFront, "^[[0-9A-Za-z]]{4}")
    if (is.na(pdbCode)) {
      message(stringr::str_c(pdbID, " is not a valid pdb id"))
      return(NA)
    }
    parsedPDB <- tryCatch(
      switch(pdbExtension,
             "cif" = bio3d::read.cif(pdbCode, verbose=F),
             "pdb" = bio3d::read.pdb(pdbCode, verbose=F)
      ),
      error = function(e) {
        message(stringr::str_c("Trouble reading pdb id: ", pdbCode, "\n", e))
        return(NA)
      }
    )
  }
  if (sum(class(parsedPDB) %in% c("pdb", "cif")) == 0) return(NA)
  ca.ind <- bio3d::atom.select(parsedPDB, "calpha")
  parsedPDB <- parsedPDB$atom[ca.ind$atom,]
  return(parsedPDB)
}

#' Downloads and prepares all pdb files specified in the module file.
#'
#' @param modFile A parsed Touchstone module file.
#' @param pdbFileDir Path to local directory containing pdb/cif file
#' @return A list of Calpha coordinates for each pdb id.
#' @seealso [parsePDB()]
#' @export
#'
gatherPDBs <- function(modFile, pdbFileDir=getwd()) {
  pdbs <- modFile$PDB.code %>% unique
  pdbs <- pdbs[!is.na(pdbs)]
  structFiles <- purrr::map(pdbs, parsePDB, pdbFileDir)
  names(structFiles) <- pdbs
  return(structFiles)
}

#' Measure euclidean distance between Calpha atoms of a crosslinked residue pair
#'
#' @param XLink.AA.1 Sequence index of 1st residue.
#' @param PDB.chain.1 PDB identifier for 1st residue.
#' @param XLink.AA.2 Sequence index of 2nd residue.
#' @param PDB.chain.2 PDB identifier for 2nd residue.
#' @param parsedPDB A parsed Touchstone pdb file.
#' @seealso [parsePDB()], [euclideanDistanceHomologous()], [euclideanHelper()]
#' @return A numeric.
#' @export
#'
euclideanDistance <- function(XLink.AA.1, PDB.chain.1, XLink.AA.2, PDB.chain.2, parsedPDB) {
  if (is.na(PDB.chain.1) | is.na(PDB.chain.2)) {
    return(NA_real_)
  } else {
    coord1 <- parsedPDB[parsedPDB$chain==PDB.chain.1 & parsedPDB$resno==XLink.AA.1,
                        c("x","y","z")]
    if (nrow(coord1)==0) coord1 <- NA
    coord2 <- parsedPDB[parsedPDB$chain==PDB.chain.2 & parsedPDB$resno==XLink.AA.2,
                        c("x","y","z")]
    if (nrow(coord2)==0) coord2 <- NA
    distance <- sqrt(sum((coord1 - coord2)**2))
    return(round(distance,2))
  }
}

#' Measure crosslinked Euclidean distances across a results table
#'
#' Calculates C-alpha to C-alpha distances for crosslinked residue pairs in a
#' parsed CLMS results table. Chain identifiers may contain comma-separated
#' homologous chain alternatives, such as `"A,D,G"`. For each crosslink, all
#' possible chain combinations are evaluated and the shortest valid distance is
#' reported.
#'
#' @param datTab Parsed CLMS search results. Must contain columns
#'   `XLink.AA.1`, `PDB.chain.1`, `XLink.AA.2`, and `PDB.chain.2`.
#' @param parsedPDB A parsed Touchstone PDB table, usually generated by
#'   [parsePDB()]. Must contain columns `chain`, `resno`, `x`, `y`, and `z`.
#' @param exclude.self Logical. If `TRUE`, candidate distances where the same
#'   atom is linked to itself are excluded. This is useful when homologous
#'   chains are supplied and a same-residue crosslink should be assigned to
#'   different subunits. Default is `TRUE`.
#'
#' @seealso [parsePDB()], [euclideanDistanceHomologous()]
#'
#' @return A data frame with `distance` and `chimera.coord` columns added.
#'
#' @export
euclideanHelper <- function(datTab, parsedPDB, exclude.self = TRUE) {

  required_cols <- c("XLink.AA.1", "PDB.chain.1", "XLink.AA.2", "PDB.chain.2")
  missing_cols <- setdiff(required_cols, colnames(datTab))

  if (length(missing_cols) > 0) {
    stop(
      "datTab is missing required column(s): ",
      paste(missing_cols, collapse = ", "),
      call. = FALSE
    )
  }

  if (is.null(parsedPDB)) {
    datTab$distance <- NA_real_
    datTab$chimera.coord <- NA_character_
    return(datTab)
  }

  pdb_required_cols <- c("chain", "resno", "x", "y", "z")
  pdb_missing_cols <- setdiff(pdb_required_cols, colnames(parsedPDB))

  if (length(pdb_missing_cols) > 0) {
    stop(
      "parsedPDB is missing required column(s): ",
      paste(pdb_missing_cols, collapse = ", "),
      call. = FALSE
    )
  }

  datTabDist <- datTab %>%
    dplyr::mutate(
      distance.temp = purrr::pmap(
        list(
          .data$XLink.AA.1,
          .data$PDB.chain.1,
          .data$XLink.AA.2,
          .data$PDB.chain.2
        ),
        euclideanDistanceHomologous,
        parsedPDB = parsedPDB,
        exclude.self = exclude.self
      ),
      distance = purrr::map_dbl(
        .data$distance.temp,
        ~ purrr::pluck(.x, "min.dist", .default = NA_real_)
      ),
      chimera.coord = purrr::map_chr(
        .data$distance.temp,
        ~ purrr::pluck(.x, "chimera.coord", .default = NA_character_)
      )
    ) %>%
    dplyr::select(-.data$distance.temp)

  return(datTabDist)
}

#' Measure Euclidean distance between C-alpha atoms for homologous chain mappings
#'
#' Calculates the shortest C-alpha to C-alpha distance for a crosslinked residue
#' pair when one or both residues can map to multiple homologous chains.
#'
#' `PDB.chain.1` and `PDB.chain.2` may be comma-separated character strings.
#' For example, if the first residue may map to chains A, D, or G, then
#' `PDB.chain.1` should be `"A,D,G"`. All possible chain combinations are
#' evaluated, and the shortest valid distance is returned.
#'
#' When `exclude.self = TRUE`, candidate pairs where the same atom is linked to
#' itself are excluded. Thus, if residue 144 can map to chains G and L, a
#' crosslink from residue 144 to residue 144 will be assigned to a cross-chain
#' pair such as `/G:144@CA /L:144@CA`, rather than `/G:144@CA /G:144@CA`.
#'
#' @param XLink.AA.1 Sequence index of the first crosslinked residue.
#' @param PDB.chain.1 PDB chain identifier(s) for the first residue. Multiple
#'   possible chains should be supplied as a comma-separated string.
#' @param XLink.AA.2 Sequence index of the second crosslinked residue.
#' @param PDB.chain.2 PDB chain identifier(s) for the second residue. Multiple
#'   possible chains should be supplied as a comma-separated string.
#' @param parsedPDB A parsed Touchstone PDB table, usually generated by
#'   [parsePDB()]. Must contain columns `chain`, `resno`, `x`, `y`, and `z`.
#' @param exclude.self Logical. If `TRUE`, candidate pairs where the same atom is
#'   linked to itself are excluded. Default is `TRUE`.
#'
#' @seealso [parsePDB()], [euclideanHelper()]
#'
#' @return A list with elements `min.dist` and `chimera.coord`.
#'
#' @export
euclideanDistanceHomologous <- function(XLink.AA.1,
                                        PDB.chain.1,
                                        XLink.AA.2,
                                        PDB.chain.2,
                                        parsedPDB,
                                        exclude.self = TRUE) {

  empty_result <- function() {
    list(
      min.dist = NA_real_,
      chimera.coord = NA_character_
    )
  }

  if (
    is.na(XLink.AA.1) || is.na(XLink.AA.2) ||
    is.na(PDB.chain.1) || is.na(PDB.chain.2)
  ) {
    return(empty_result())
  }

  chain1_vec <- stringr::str_split(PDB.chain.1, ",")[[1]] %>%
    stringr::str_trim()

  chain2_vec <- stringr::str_split(PDB.chain.2, ",")[[1]] %>%
    stringr::str_trim()

  chain1_vec <- chain1_vec[chain1_vec != ""]
  chain2_vec <- chain2_vec[chain2_vec != ""]

  if (length(chain1_vec) == 0 || length(chain2_vec) == 0) {
    return(empty_result())
  }

  get_ca_coord <- function(parsedPDB, query_chain, query_resno) {
    coord <- parsedPDB %>%
      dplyr::filter(
        .data$chain == query_chain,
        .data$resno == query_resno
      )

    coord <- coord %>%
      dplyr::select(dplyr::all_of(c("x", "y", "z")))

    if (nrow(coord) == 0) {
      return(NULL)
    }

    # If duplicate coordinates exist, use the first one.
    as.numeric(coord[1, c("x", "y", "z")])
  }

  candidates <- tidyr::expand_grid(
    chain1 = chain1_vec,
    chain2 = chain2_vec
  )

  same_residue <- as.character(XLink.AA.1) == as.character(XLink.AA.2)

  if (exclude.self && isTRUE(same_residue)) {
    candidates <- candidates %>%
      dplyr::filter(.data$chain1 != .data$chain2)
  }
  if (nrow(candidates) == 0) {
    return(empty_result())
  }

  distanceBox <- numeric(0)
  chainPairBox <- character(0)

  for (i in seq_len(nrow(candidates))) {

    chain1 <- candidates$chain1[i]
    chain2 <- candidates$chain2[i]

    coord1 <- get_ca_coord(parsedPDB, chain1, XLink.AA.1)
    coord2 <- get_ca_coord(parsedPDB, chain2, XLink.AA.2)

    if (is.null(coord1) || is.null(coord2)) {
      distance <- NA_real_
    } else {
      distance <- sqrt(sum((coord1 - coord2)^2))
    }

    chainPair <- stringr::str_c(
      "/", chain1, ":", XLink.AA.1, "@CA ",
      "/", chain2, ":", XLink.AA.2, "@CA"
    )

    distanceBox <- c(distanceBox, distance)
    chainPairBox <- c(chainPairBox, chainPair)
  }

  if (length(distanceBox) == 0 || all(is.na(distanceBox))) {
    return(empty_result())
  }

  return.index <- which.min(distanceBox)

  list(
    min.dist = round(distanceBox[return.index], 2),
    chimera.coord = chainPairBox[return.index]
  )
}

#' #' Measure crosslinked euclidean distances over the entire results file.
#' #'
#' #' @param datTab Parsed CLMS search results.
#' #' @param parsedPDB A parsed Touchstone pdb file.
#' #' @seealso [parsePDB()], [euclideanDistanceHomologous()]
#' #' @return A data frame.
#' #' @export
#' #'
#' euclideanHelper <- function(datTab, parsedPDB) {
#'   if (!is.null(parsedPDB)) {
#'     datTabDist <- datTab %>%
#'       #      mutate(distance = purrr::pmap_dbl(., euclideanDistanceHomologous, parsedPDB))
#'       mutate(distance.temp = purrr::pmap(
#'         list(.data$XLink.AA.1, .data$PDB.chain.1, .data$XLink.AA.2, .data$PDB.chain.2),
#'         euclideanDistanceHomologous,
#'         parsedPDB),
#'         distance = map_dbl(distance.temp, ~ pluck(.x, 1, .default = NA_real_)),
#'         chimera.coord = map_chr(distance.temp, ~ pluck(.x, 2, .default = NA_character_))
#'       ) %>%
#'       select(-distance.temp)
#'   } else {
#'     datTabDist <- datTab %>%
#'       mutate(distance = NA_real_)
#'   }
#'   return(datTabDist)
#' }
#'
#' #' Measure euclidean distance between Calpha atoms of a crosslinked residue pair when there are homologous results.
#' #'
#' #' `euclideanDistanceHomologous()` expects that all possible chain ids are supplied as
#' #' a comma separated character string. For instance is the first crosslinked residue can
#' #' be either position 100 on either chain A, D, G, `XLink.AA.1` value should be `100` and
#' #' the `PDB.chain.1` should be given as `"A, D, G"`. All possible euclidean distances
#' #' are evaluated, and the shortest distance is reported. This function is meant to
#' #' handle cases in which a protein complex has multiple copies of the same subunit,
#' #' rather than situations where the crosslinked peptide appears in multiple different
#' #' homologous proteins.
#' #' @param XLink.AA.1 Sequence index of 1st residue.
#' #' @param PDB.chain.1 PDB identifier for 1st residue.
#' #' @param XLink.AA.2 Sequence index of 2nd residue.
#' #' @param PDB.chain.2 PDB identifier for 2nd residue.
#' #' @param parsedPDB A parsed Touchstone pdb file.
#' #' @seealso [parsePDB()], [euclideanDistance()], [euclideanHelper()]
#' #' @return A numeric.
#' #' @export
#' #'
#' euclideanDistanceHomologous <- function(XLink.AA.1, PDB.chain.1, XLink.AA.2, PDB.chain.2, parsedPDB) {
#'   PDB.chain.1 <- stringr::str_remove_all(PDB.chain.1, "\\s+")
#'   PDB.chain.2 <- stringr::str_remove_all(PDB.chain.2, "\\s+")
#'   if (is.na(PDB.chain.1) | is.na(PDB.chain.2)) {
#'     return(NA_real_)
#'   } else {
#'     distanceBox <- numeric()
#'     chainPairBox <- character()
#'     index <- 1
#'     for (chain1 in stringr::str_split(PDB.chain.1, ",")[[1]]) {
#'       for (chain2 in stringr::str_split(PDB.chain.2, ",")[[1]]) {
#'         coord1 <- parsedPDB[parsedPDB$chain==chain1 & parsedPDB$resno==XLink.AA.1,
#'                             c("x","y","z")]
#'         if (nrow(coord1)==0) coord1 <- NA
#'         coord2 <- parsedPDB[parsedPDB$chain==chain2 & parsedPDB$resno==XLink.AA.2,
#'                             c("x","y","z")]
#'         if (nrow(coord2)==0) coord2 <- NA
#'         distance <- sqrt(sum((coord1 - coord2)**2))
#'         distanceBox[index] <- distance
#'         chainPair <- stringr::str_c("/", chain1, ":", XLink.AA.1, "@CA ",
#'                                     "/", chain2, ":", XLink.AA.2, "@CA",
#'                                     sep = "")
#'         chainPairBox[index] <- chainPair
#'         index <- index + 1
#'       }
#'     }
#'     if (sum(is.na(distanceBox)) == length(distanceBox)) {
#'       return(NA)
#'     } else {
#'       return.index <- which.min(distanceBox)
#'       return(list(
#'         min.dist = round(distanceBox[return.index], 2),
#'         chimera.coord = chainPairBox[return.index]
#'         ))
#'     }
#'   }
#' }

#' Sample random C-alpha distances on a PDB structure.
#'
#' Generates a distribution of random C-alpha, C-alpha distances on a PDB structure.
#' The size of the distibution is given my `numCrosslinks`. By default, only Lys-Lys
#' pairs are sampled, but this can be changed with the `resType` parameters.
#'
#' @param parsedPDB A parsed Touchstone pdb file.
#' @param numCrosslinks Number of random crosslinks generated.
#' @param resType1 A character vector containing three letter amino acid codes, from which the random crosslinks are selected.
#' @param resType2 A character vector containing three letter amino acid codes, from which the random crosslinks are selected.
#' @param chains If not `null`, restrict the random distribution to certain chains, given in a character vector.
#' @seealso [randomHelper()]
#' @return A numeric vector.
#' @export
#'
randomCrosslinks <- function(parsedPDB, numCrosslinks,
                             resType1="LYS", resType2="LYS",
                             chains=NULL) {
  if (!is.null(chains)) {
    parsedPDB <- parsedPDB %>% filter(.data$chain %in% chains)
  }
  pdb1 <- parsedPDB %>%
    filter(.data$resid %in% resType1) %>%
    dplyr::slice_sample(n=numCrosslinks, replace=T) %>%
    select(XLink.AA.1=.data$resno, PDB.chain.1=.data$chain)
  pdb2 <- parsedPDB %>%
    filter(.data$resid %in% resType2) %>%
    dplyr::slice_sample(n=numCrosslinks, replace=T) %>%
    select(XLink.AA.2=.data$resno, PDB.chain.2=.data$chain)
  pdb <- cbind(pdb1, pdb2)
  randomDists <- pdb %>%
    purrr::pmap_dbl(euclideanDistance, parsedPDB)
  return(randomDists)
}

#' Generate random distributions of crosslinked euclidean distances across a dataset.
#'
#' @param datTab Parsed CLMS search results.
#' @param parsedPDB A parsed Touchstone pdb file.
#' @param resType1 A character vector containing three letter amino acid codes, from which the random crosslinks are selected.
#' @param resType2 A character vector containing three letter amino acid codes, from which the random crosslinks are selected.
#' @param chains If not `null`, restrict the random distribution to certain chains, given in a character vector.
#' @seealso [randomCrosslinks()]
#' @return A data frame.
#' @export
#'
randomHelper <- function(datTab, parsedPDB, resType1="LYS", resType2="LYS", chains=NULL) {
  if (!is.null(parsedPDB)) {
    numCrosslinks <- nrow(datTab)
    datTab$random.distance <- randomCrosslinks(parsedPDB, numCrosslinks,
                                               resType1, resType2, chains)
  } else {
    datTab$random.distance <- NA_real_
  }
  return(datTab)
}

#' Measure crosslinked and randomized distributions of euclidean distances for a dataset.
#'
#' For each pdb id assigned in the module file, euclidean crosslinked and randomized
#' Calpha-Calpha distance distributions are measured and assigned to the dataset.
#'
#' @param datTabMod Parsed CLMS search results, with modules and chain ids assigned.
#' @param pdbList A list of pdb ids.
#' @seealso [processModuleFile()], [euclideanHelper()], [randomHelper()]
#' @return a data frame
#' @export
#'
measureCrosslinkDistance <- function(datTabMod, pdbList) {
  nestedDatTabMod <- datTabMod %>%
    group_by(.data$PDB) %>%
    nest(.key="data.nested")
  if (sum(is.na(nestedDatTabMod$PDB)) > 0) {
    nestedDatTabNA <- nestedDatTabMod %>%
      filter(is.na(.data$PDB)) %>%
      unnest(cols=c(.data$data.nested)) %>%
      ungroup() %>%
      mutate(random.distance = NA_real_)
  } else {
    nestedDatTabNA <- data.frame()
  }
  nestedDatTabMod <- nestedDatTabMod %>%
    filter(!is.na(.data$PDB)) %>%
    mutate(parsedPDB = pdbList[.data$PDB]) %>%
    mutate(data.nested=purrr::map2(.data$data.nested, .data$parsedPDB, euclideanHelper)) %>%
    mutate(data.nested=purrr::map2(.data$data.nested, .data$parsedPDB, randomHelper)) %>%
    select(-.data$parsedPDB) %>%
    unnest(cols=c(.data$data.nested)) %>%
    ungroup()
  bind_rows(nestedDatTabMod, nestedDatTabNA) %>%
    relocate(.data$PDB, .after=.data$PDB.chain.2)
}

#' Parse a Touchstone formatted module file.
#'
#' @param pathToModFile Location of module file.
#' @return A data frame.
#' @export
#'
readModuleFile <- function(pathToModFile) {
  modFile <- read_tsv(pathToModFile,
                      col_types = cols(
                        Acc = col_character(),
                        Protein.name = col_character(),
                        Module = col_character(),
                        PDB.code = col_character(),
                        PDB.chain = col_character(),
                        first.AA = col_integer(),
                        last.AA = col_integer()
                      )
  )
  if (sum(is.na(modFile$last.AA)) > 0) {

    # If the first/last AA columns are missing from mod file, create them.
    # get protein lengths from Uniprot... it might be more efficient, to force
    # Prospector to output sequence length in search compare and use instead.
    if (!"first.AA" %in% names(modFile)) {
      modFile$first.AA <- 0L
    }
    if (!"last.AA" %in% names(modFile)) {
      modFile$last.AA <- purrr::map_int(modFile$Acc, getUniprotSeqLength(modFile$Acc))
    }

    # If some entries don't have first/last NA specified, eg... there is some
    # domain of particular interest, but rest of the protein should default to some
    # other module, then first.AA needs to be NA.  Fill in last.AA to protein length
    # for purpose of displaying XiNet visualizations correctly.
    modFile <- modFile %>%
      mutate(last.AA = purrr::map2_int(.data$last.AA, .data$Acc, function(last.AA, Acc) {
        if(is.na(last.AA)) {
          return(getUniprotSeqLength(Acc))
        } else {
          return(as.integer(last.AA))
        }
      }))
    tryCatch(readr::write_tsv(modFile, pathToModFile),
             error = function(e) {
               message(stringr::str_c("Could not write module file: ", e))
               return(modFile)
             }
    )
  }
  modFile <- modFile %>%
    select(.data$Acc, .data$Protein.name, .data$Module, .data$first.AA, .data$last.AA,
           any_of(c("PDB.code", "PDB.chain")))
  return(modFile)
}

#' Returns the length of a protein sequence in number of AA residues.
#'
#' @param uniprotAcc A valid Uniprot Accession Number.
#' @returns an integer
#' @export
#'
getUniprotSeqLength <- function(uniprotAcc) {
  seqLen <- tryCatch(
    {seq <- bio3d::uniprot(uniprotAcc)$sequence
    proteinLen <- nchar(seq)
    },
    error = function(e) {
      message(stringr::str_c("trouble accessing Uniprot ID: ", uniprotAcc, "\n", e))
      return(50000L)
    }
  )
}

#' Assigns crosslinks to modules defined in a Touchstone formatted module file
#'
#' @param datTab Parsed CLMS search results.
#' @param moduleFile Parsed, Touchstone format module file
#' @returns a data frame
#' @export
#'
assignModules <- function(datTab, moduleFile) {
  datTab <- datTab %>%
    select(-any_of(c(starts_with("xlinkedModulPair"), starts_with("Module."), starts_with("PDB.code."), starts_with("PDB.chain."))))
  mods <- unique(moduleFile$Module) %>% stringr::str_sort()
  accs <- sort(unique(as.character(c(datTab$Acc.1, datTab$Acc.2))))
  datTab <- datTab %>% group_by(.data$Decoy2)
  datTabList <- datTab %>% group_split()
  names(datTabList) <- datTab %>% group_keys() %>% pull(.data$Decoy2)
  datTab.target <- datTabList$Target %>%
    left_join(moduleFile, by=c("Acc.1"="Acc"), relationship = "many-to-many") %>%
    mutate("keepEntry" = suppressWarnings(purrr::pmap_lgl(select(., .data$XLink.AA.1, .data$first.AA, .data$last.AA),
                                                         function(XLink.AA.1, first.AA, last.AA)
                                                           dplyr::between(XLink.AA.1, first.AA, last.AA))
    )) %>%
    filter(.data$keepEntry | is.na(.data$keepEntry)) %>%
    group_by(.data$Fraction, .data$MSMS.Info, .data$xlinkedResPair) %>%
    add_count(name="redundance") %>%
    filter(.data$redundance == 1 | (.data$redundance > 1 & .data$keepEntry)) %>%
    ungroup() %>%
    select(-.data$first.AA, -.data$last.AA, -.data$keepEntry, -.data$Protein.name, -.data$redundance) %>%
    left_join(moduleFile, by=c("Acc.2"="Acc"), suffix=c(".1", ".2"), relationship = "many-to-many") %>%
    mutate("keepEntry" = suppressWarnings(purrr::pmap_lgl(select(., .data$XLink.AA.2, .data$first.AA, .data$last.AA),
                                                         function(XLink.AA.2, first.AA, last.AA)
                                                           dplyr::between(XLink.AA.2, first.AA, last.AA))
    )) %>%
    filter(.data$keepEntry | is.na(.data$keepEntry)) %>%
    group_by(.data$Fraction, .data$MSMS.Info, .data$xlinkedResPair) %>%
    add_count(name="redundance") %>%
    filter(.data$redundance == 1 | (.data$redundance > 1 & .data$keepEntry)) %>%
    ungroup() %>%
    select(-.data$first.AA, -.data$last.AA, -.data$keepEntry, -.data$Protein.name, -.data$redundance) %>%
    mutate(xlinkedModulPair = ifelse(.data$Module.1 <= .data$Module.2,
                                     stringr::str_c(.data$Module.1, .data$Module.2, sep="::"),
                                     stringr::str_c(.data$Module.2, .data$Module.1, sep="::"))
    ) %>%
    mutate(xlinkedModulPair = forcats::as_factor(.data$xlinkedModulPair),
           Module.1 = factor(.data$Module.1, levels = mods),
           Module.2 = factor(.data$Module.2, levels = mods),
           Acc.1 = factor(.data$Acc.1, levels = accs),
           Acc.2 = factor(.data$Acc.2, levels = accs)) #%>%
  #         add_count(xlinkedModulPair, name="numMPSM")
  if (sum(stringr::str_detect(names(datTab.target), "PDB.code")) > 0) {
    datTab.target <- datTab.target %>%
      mutate(PDB = ifelse(!is.na(.data$PDB.code.1) & !is.na(.data$PDB.code.2) & .data$PDB.code.1 == .data$PDB.code.2,
                          .data$PDB.code.1, NA)
      )
  }
  if (length(datTabList) == 2) {
    datTab.decoy <- datTabList$Decoy
    decoyLength <- nrow(datTab.decoy)
    colsToAdd <- setdiff(names(datTab.target), names(datTab.decoy))
    emptyCols <- matrix(nrow=decoyLength, ncol=length(colsToAdd))
    colnames(emptyCols) <- colsToAdd
    emptyCols <- as_tibble(emptyCols)
    datTab.decoy <- bind_cols(datTab.decoy, emptyCols)
    datTab <- bind_rows(datTab.target, datTab.decoy)
  } else {
    datTab <- datTab.target
  }
  return(datTab)
}

#' Wrapper function that assigns modules and distances defined in a Touchstone Module File
#'
#' @param datTab Parsed CLMS search results.
#' @param pathToModFile Location of module file
#' @param pdbFileDir Path to local directory containing pdb/cif file
#' @returns a data frame
#' @export
#'
processModuleFile <- function(datTab, pathToModFile, pdbFileDir = getwd()) {
  modFile <- readModuleFile(pathToModFile)
  datTab <- assignModules(datTab, modFile)
  if ("PDB.code" %in% names(modFile) & sum(!is.na(datTab$PDB) > 0)) {
    pdbFiles <- gatherPDBs(modFile, pdbFileDir = pdbFileDir)
    datTab <- measureCrosslinkDistance(datTab, pdbFiles)
  }
  return(datTab)
}

#' Make a ChimeraX pseudobond file from crosslink coordinates
#'
#' Creates the text for a ChimeraX pseudobond (`.pb`) file from a crosslink
#' results table. Crosslinks with distances less than or equal to `threshold`
#' are colored with `pass.color`; crosslinks above `threshold` are colored with
#' `viol.color`. Self-links, where the same atom is linked to itself, are
#' removed.
#'
#' The input table must contain columns named `PDB`, `distance`, and
#' `chimera.coord`. The `PDB` column is used as a sanity check. If multiple PDB
#' identifiers are present in `datTab`, the function stops and asks the user to
#' make separate pseudobond files for each structure.
#'
#' Atom coordinates in `chimera.coord` should be formatted as ChimeraX atom
#' pairs, for example `"/A:123@CA /B:456@CA"`. These are automatically generated
#' when calling `measureEuclideanDistanceHomologous`. If atom specifications do not
#' already include a ChimeraX model identifier, `model.id` is prepended, giving
#' entries such as `"#1/A:123@CA #1/B:456@CA"`.
#'
#' @param datTab A data frame containing crosslink results. Must contain columns
#'   `PDB`, `distance`, and `chimera.coord`.
#' @param pdb.code Optional character string giving the PDB code or file name
#'   shown in the header comment. If `NULL`, the unique value from `datTab$PDB`
#'   is used.
#' @param threshold Numeric distance threshold used to separate satisfied and
#'   violating crosslinks. Default is `35`.
#' @param model.id ChimeraX model identifier to prepend to atom specifications
#'   that do not already contain a model prefix. Can be supplied as `"#1"` or
#'   `1`. Default is `"#1"`.
#' @param pass.color Color for crosslinks with `distance <= threshold`.
#'   Default is `"limegreen"`.
#' @param viol.color Color for crosslinks with `distance > threshold`.
#'   Default is `"red"`.
#' @param radius Numeric pseudobond radius. Default is `0.5`.
#' @param dashes Number of dashes for pseudobonds. Default is `12`.
#' @param out.file Optional output file path. If supplied, the pseudobond text is
#'   written to this file.
#'
#' @return A character string containing the ChimeraX pseudobond file text.
#' @export
makeChimeraXpbondFile <- function(datTab,
                                  pdb.code = NULL,
                                  threshold = 35,
                                  model.id = "#1",
                                  pass.color = "limegreen",
                                  viol.color = "red",
                                  radius = 0.5,
                                  dashes = 12,
                                  out.file = NULL) {

  required_cols <- c("PDB", "distance", "chimera.coord")
  missing_cols <- setdiff(required_cols, colnames(datTab))

  if (length(missing_cols) > 0) {
    stop(
      "datTab is missing required column(s): ",
      paste(missing_cols, collapse = ", "),
      call. = FALSE
    )
  }

  if (!is.numeric(threshold) || length(threshold) != 1 || is.na(threshold)) {
    stop("threshold must be a single numeric value.", call. = FALSE)
  }

  if (!is.numeric(radius) || length(radius) != 1 || is.na(radius)) {
    stop("radius must be a single numeric value.", call. = FALSE)
  }

  if (!is.numeric(dashes) || length(dashes) != 1 || is.na(dashes)) {
    stop("dashes must be a single numeric value.", call. = FALSE)
  }

  # Normalize model.id so either 1 or "#1" works.
  model.id <- as.character(model.id)

  if (length(model.id) != 1 || is.na(model.id) || model.id == "") {
    stop("model.id must be a single non-empty value, e.g. '#1' or 1.", call. = FALSE)
  }

  if (!startsWith(model.id, "#")) {
    model.id <- paste0("#", model.id)
  }

  pdb.values <- unique(stats::na.omit(datTab$PDB))

  if (length(pdb.values) > 1) {
    stop(
      "Multiple PDB values were found in datTab: ",
      paste(pdb.values, collapse = ", "),
      "\nPlease make separate ChimeraX pseudobond files for each PDB.",
      call. = FALSE
    )
  }

  if (is.null(pdb.code)) {
    if (length(pdb.values) == 0) {
      stop(
        "pdb.code was not supplied and datTab$PDB contains no usable PDB value.",
        call. = FALSE
      )
    }

    pdb.code <- pdb.values
  } else {
    pdb.code <- as.character(pdb.code)

    if (length(pdb.code) != 1 || is.na(pdb.code) || pdb.code == "") {
      stop("pdb.code must be NULL or a single non-empty value.", call. = FALSE)
    }

    if (length(pdb.values) == 1 && pdb.values != pdb.code) {
      warning(
        "Supplied pdb.code does not match datTab$PDB. ",
        "pdb.code = ", pdb.code, "; datTab$PDB = ", pdb.values,
        call. = FALSE
      )
    }
  }

  prefix_model <- function(atom_spec) {
    atom_spec <- stringr::str_trim(atom_spec)

    if (stringr::str_starts(atom_spec, "#")) {
      atom_spec
    } else {
      paste0(model.id, atom_spec)
    }
  }

  clean_pbonds <- function(x) {
    x <- as.character(x)
    x <- x[!is.na(x)]

    pbonds <- stringr::str_split(x, "\n") |>
      unlist(use.names = FALSE) |>
      stringr::str_trim()

    pbonds <- pbonds[pbonds != ""]

    if (length(pbonds) == 0) {
      return(character(0))
    }

    cleaned <- purrr::map_chr(pbonds, function(line) {
      atoms <- stringr::str_split(line, "\\s+")[[1]]
      atoms <- atoms[atoms != ""]

      if (length(atoms) != 2) {
        warning("Skipping malformed pseudobond line: ", line, call. = FALSE)
        return(NA_character_)
      }

      atoms <- vapply(atoms, prefix_model, character(1))

      # Remove same-atom self-links after model prefixing.
      if (identical(atoms[1], atoms[2])) {
        return(NA_character_)
      }

      paste(atoms, collapse = " ")
    })

    cleaned <- cleaned[!is.na(cleaned)]
    unique(cleaned)
  }

  chimera.pbond.header <- stringr::str_glue(
    "; open this pbond file after command: open {pdb.code}
; model = {model.id}
; halfbond = false
; color = {pass.color}
; radius = {radius}
; dashes = {dashes}
"
  )

  chimera.pdbonds <- datTab |>
    dplyr::filter(.data$distance <= threshold) |>
    dplyr::pull(.data$chimera.coord) |>
    clean_pbonds()

  chimera.pdbonds.viol <- datTab |>
    dplyr::filter(.data$distance > threshold) |>
    dplyr::pull(.data$chimera.coord) |>
    clean_pbonds()

  pbond.parts <- c(
    chimera.pbond.header,
    chimera.pdbonds,
    if (length(chimera.pdbonds.viol) > 0) stringr::str_glue("; color = {viol.color}"),
    chimera.pdbonds.viol
  )

  pbondFile <- stringr::str_c(pbond.parts, collapse = "\n")

  if (!is.null(out.file)) {
    writeLines(pbondFile, con = out.file)
  }

  return(pbondFile)
}
