#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr add_count
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr group_keys
#' @importFrom dplyr group_split
#' @importFrom dplyr if_else
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarize
#' @importFrom dplyr tally
#' @importFrom dplyr ungroup
#' @importFrom future plan
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_path
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 scale_alpha
#' @importFrom ggplot2 scale_alpha_manual
#' @importFrom ggplot2 scale_color_brewer
#' @importFrom ggplot2 scale_color_gradient2
#' @importFrom ggplot2 scale_color_viridis_c
#' @importFrom ggplot2 scale_fill_brewer
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_size_area
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylab
#' @importFrom graphics abline
#' @importFrom graphics hist
#' @importFrom graphics legend
#' @importFrom graphics title
#' @importFrom grDevices rgb
#' @importFrom methods is
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_dbl
#' @importFrom purrr map_dfr
#' @importFrom purrr map_int
#' @importFrom purrr map_lgl
#' @importFrom purrr pluck
#' @importFrom readr col_character
#' @importFrom readr col_integer
#' @importFrom readr cols
#' @importFrom readr read_tsv
#' @importFrom stats median
#' @importFrom stats predict
#' @importFrom stats sd
#' @importFrom tibble add_column
#' @importFrom tibble as_tibble
#' @importFrom tibble column_to_rownames
#' @importFrom tibble tibble
#' @importFrom tidyr complete
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr unnest
#' @importFrom tidyselect any_of
#' @importFrom tidyselect everything
#' @importFrom tidyselect starts_with
## usethis namespace: end
NULL
